"use client";
import {useState} from "react";
import dynamic from "next/dynamic";
import {Chrome,Scene,EndLinks,useJourney} from "../journey";
import {range} from "../data";
const Spatial=dynamic(()=>import("../spatial/Spatial"),{ssr:false});
export default function Ghost(){const {progress:p,jump}=useJourney();const [unit,setUnit]=useState("Carbon");
 return <main className="journey ghost" style={{height:"790svh"}}><div className="pinned-world"><div className="ghost-ambient"/><div className="ghost-backtype" aria-hidden="true" style={{transform:`translateX(${-p*28}%)`,opacity:.045+range(p,.2,.4)*.04}}>{p<.33?"PRESENCE":p<.65?"ECHO":"CONTINUITY"}</div><Spatial mode="ghost" progress={p}/><div className="ghost-floor-label meta">{p<.17?"OBJECT 001 / A LIVING ORGANISM":p<.35?"RETURN SIGNAL / INCOMPLETE":p<.65?"POINT CLOUD / RECONSTRUCTED":p<.84?"MASS / ESTIMATED":"OBSERVATION / CONTINUOUS"}</div><div className="ghost-height-axis" style={{opacity:range(p,.40,.53)}}><span>32.4 m</span><i/><span>GROUND RETURN / 0 m</span></div>
 <Scene progress={p} index={0} className="ghost-opening"><p className="eyebrow">04 / GHOST FOREST</p><h1>It was<br/><em>here.</em></h1><p className="scene-subtitle">A tree is a world. <br/>What happens when that world disappears?</p><button className="ghost-enter" onClick={()=>jump(1)}>FOLLOW THE ECHO <span>↓</span></button></Scene>
 <Scene progress={p} index={1} className="ghost-copy"><p className="eyebrow">01 / ERASURE</p><h2>Gone.<br/>But not<br/><em>without a trace.</em></h2><p>The canopy breaks apart. <br/>Habitat, biomass, and stored carbon <br/>leave a measurable absence.</p><span className="ghost-counter">−18.4 pp <small>CANOPY / SIMULATED CHANGE</small></span></Scene>
 <Scene progress={p} index={2} className="ghost-copy"><p className="eyebrow">02 / THE RETURN</p><h2>Even absence<br/>has a <em>signal.</em></h2><p>Field observations leave gaps in space and time. <br/>Satellite revisits let us listen between them.</p><div className="ghost-signals"><span>01 / OPTICAL REFLECTANCE</span><span>02 / RADAR BACKSCATTER</span><span>03 / LASER RETURNS</span></div></Scene>
 <Scene progress={p} index={3} className="ghost-copy"><p className="eyebrow">03 / RECONSTRUCTION</p><h2>A million points.<br/>One <em>living form.</em></h2><p>SylvaSense connects multispectral imagery, <br/>Sentinel-1 radar, and LiDAR structure. <br/>A canopy resolves into individual trees.</p><div className="ghost-counter">12,486 <small>CANOPY INSTANCES / STUDY AREA</small></div></Scene>
 <Scene progress={p} index={4} className="ghost-copy"><p className="eyebrow">04 / WHAT REMAINS UNSEEN</p><h2>The weight<br/>of <em>being alive.</em></h2><p>Structure becomes an estimate of biomass. <br/>Biomass becomes a carbon stock estimate.</p><div className="ghost-unit-tabs">{["Carbon","Biomass"].map(x=><button key={x} aria-pressed={unit===x} onClick={()=>setUnit(x)}>{x}</button>)}</div><div className="ghost-counter">{unit==="Carbon"?"86.8":"184.6"} <small>{unit==="Carbon"?"Mg C / ha · stored carbon":"Mg / ha · aboveground biomass"}</small></div><p className="small-copy">Carbon stock is not annual sequestration. <br/>Change requires repeat observations.</p></Scene>
 <Scene progress={p} index={5} className="ghost-copy"><p className="eyebrow">05 / CONTINUITY</p><h2>Make the living<br/><em>impossible to ignore.</em></h2><p>Compare the returns. Locate the loss. <br/>Turn the echo into verifiable action.</p><EndLinks id="04"/></Scene>
 </div><Chrome id="04" progress={p} jump={jump}/></main>;
}
