"use client";
import {useState} from "react";
import {Chrome,Scene,EndLinks,Film,useJourney} from "../journey";
import {clamp,range,random} from "../data";

export default function LastBreath(){
  const {progress:p,jump,reduced}=useJourney();const [layer,setLayer]=useState("Canopy");
  const loss=range(p,.12,.30),observe=range(p,.40,.55),renew=range(p,.78,.90);
  return <main className="journey breath" style={{height:"740svh"}}><div className="pinned-world">
    <div className="breath-world" style={{transform:`scale(${1+(reduced?0:p*.32)})`,filter:`saturate(${1-loss*.95+observe*.55}) brightness(${.76-loss*.38+observe*.13+renew*.25})`}}><Film active={p<.32}/><div className="breath-canopy" style={{opacity:observe}}/><div className="breath-mist" style={{opacity:clamp(1-observe*1.6),transform:`translate3d(${p*-15}%,${p*-8}%,0) scale(1.15)`}}/></div>
    <div className="breath-vignette"/>
    <div className="absence-field" aria-hidden="true">{Array.from({length:32},(_,i)=><i key={i} style={{left:`${(random(i)*100).toFixed(2)}%`,top:`${(random(i+90)*100).toFixed(2)}%`,width:`${(6+random(i+33)*18).toFixed(2)}vw`,height:`${(8+random(i+24)*22).toFixed(2)}vh`,opacity:clamp((loss-random(i+6)*.6)*1.8)*(1-renew)*(1-observe*.95),transform:`scale(${.6+loss*.6}) rotate(${(random(i+51)*60).toFixed(2)}deg)`}}/>)}</div>
    <div className="breath-grid" style={{opacity:observe*(1-renew*.7),transform:`perspective(900px) rotateX(${(1-observe)*40}deg)`}}/>
    <div className={`canopy-segments layer-${layer.toLowerCase()}`} style={{opacity:range(p,.50,.58)*(1-renew*.75)}} aria-hidden="true">{Array.from({length:38},(_,i)=><span key={i} style={{left:`${(3+random(i+24)*92).toFixed(2)}%`,top:`${(12+random(i+74)*72).toFixed(2)}%`,width:`${(22+random(i)*75).toFixed(2)}px`,height:`${(24+random(i)*65).toFixed(2)}px`}}><small>T{(240+i).toString()}</small></span>)}</div>
    <div className="breath-scan" style={{opacity:observe*(1-renew),left:`${(p*400)%100}%`}}/>
    <div className="breath-orbit-caption meta" style={{opacity:observe}}>AOI 04 / WESTERN GHATS<br/>11.68° N · 76.18° E<br/><span>ILLUSTRATIVE OBSERVATION</span></div>
    <Scene progress={p} index={0} className="breath-opening"><p className="eyebrow">01 / THE LAST BREATH</p><h1>Listen to<br/>what is <em>living.</em></h1><p className="scene-subtitle">A million quiet lives. <br/>One extraordinary, connected world.</p><div className="breath-coordinate meta">A FOREST IS MORE THAN THE SUM OF ITS TREES.</div><button className="circle-cta" onClick={()=>jump(1)} aria-label="Enter the forest story">↓</button></Scene>
    <Scene progress={p} index={1} className="breath-loss"><p className="eyebrow">02 / THE SILENCE BETWEEN TREES</p><h2>Then, a little<br/>less <em>life.</em></h2><p className="scene-subtitle">A clearing becomes a corridor. <br/>The canopy thins before the forest is gone.</p><div className="loss-number">−{(loss*18.4).toFixed(1)}<span>pp</span><small>CANOPY COVER IN THIS SIMULATED STUDY</small></div></Scene>
    <Scene progress={p} index={2} className="breath-distance"><p className="eyebrow">03 / A PROBLEM OF PERSPECTIVE</p><h2>We cannot protect<br/>what we <em>cannot see.</em></h2><p className="scene-subtitle">Field visits reveal a place. They cannot be everywhere. <br/>Slow degradation slips between the observations.</p><div className="observation-gap"><span>ONE FIELD VISIT</span><i/><span>EVERYTHING THAT HAPPENED BETWEEN</span><i/><span>THE NEXT</span></div></Scene>
    <Scene progress={p} index={3} className="breath-observe"><p className="eyebrow">04 / A DIFFERENT KIND OF SIGHT</p><h2>The forest.<br/><em>Revealed.</em></h2><p className="scene-subtitle">Optical imagery reads vegetation. Radar sees through cloud. <br/>LiDAR gives the canopy its third dimension.</p><div className="sensor-list"><span>01 Sentinel-2 / Landsat</span><span>02 Sentinel-1 SAR</span><span>03 LiDAR height returns</span></div></Scene>
    <Scene progress={p} index={4} className="breath-measure"><p className="eyebrow">05 / FROM SIGNAL TO UNDERSTANDING</p><h2>Every crown.<br/>Every <em>consequence.</em></h2><p className="scene-subtitle">SylvaSense connects the signals: individual canopies, <br/>estimated biomass, stored carbon, and change over time.</p><div className="layer-tabs" aria-label="Forest measurement layer">{["Canopy","Biomass","Carbon"].map(x=><button key={x} aria-pressed={layer===x} onClick={()=>setLayer(x)}>{x}</button>)}</div><div className="breath-reading"><strong>{layer==="Canopy"?"12,486":layer==="Biomass"?"184.6":"86.8"}</strong><span>{layer==="Canopy"?"individual crowns identified":layer==="Biomass"?"Mg / ha · estimated aboveground biomass":"Mg C / ha · estimated stored carbon"}</span></div></Scene>
    <Scene progress={p} index={5} className="breath-ending"><p className="eyebrow">06 / INTELLIGENCE FOR A LIVING PLANET</p><h2>Let the next chapter<br/>be <em>alive.</em></h2><p className="scene-subtitle">Observe the change. Verify the loss. Focus the response. <br/>SylvaSense makes a forest’s story visible.</p><EndLinks id="01"/></Scene>
  </div><Chrome id="01" progress={p} jump={jump}/></main>;
}
