"use client";
import {useState} from "react";
import dynamic from "next/dynamic";
import {Chrome,Scene,EndLinks,useJourney} from "../journey";
const Spatial=dynamic(()=>import("../spatial/Spatial"),{ssr:false});
export default function Orbit(){const {progress:p,jump}=useJourney();const [band,setBand]=useState("OPTICAL");
 return <main className="journey orbit" style={{height:"800svh"}}><div className="pinned-world"><Spatial mode="orbit" progress={p} band={band}/><div className="orbit-grain"/><div className="orbit-corner corner-tl"/><div className="orbit-corner corner-br"/><div className="orbital-readout meta"><span>MISSION SYLVA / 042</span><span>ALT {Math.round(786*(1-Math.min(1,p*1.5))+11).toString().padStart(3,"0")} KM</span><span>PASS {Math.floor(139+p*24)}</span></div><div className="orbit-reticle" aria-hidden="true">+<small>11°41′ N / 76°10′ E</small></div>
  <Scene progress={p} index={0} className="orbit-opening"><p className="eyebrow">02 / ORBITAL INTELLIGENCE</p><h1>Distance<br/>changes<br/><span>everything.</span></h1><p className="scene-subtitle">From here, a forest becomes a system. <br/>And every change leaves a signal.</p><button className="technical-button" onClick={()=>jump(1)}>BEGIN ORBITAL PASS <span>↗</span></button></Scene>
  <Scene progress={p} index={1} className="orbit-copy"><p className="eyebrow">01 — THE OBSERVATION GAP</p><h2>A green planet.<br/>An incomplete<br/><span>picture.</span></h2><p>Cloud. Distance. Time between field surveys. <br/>A forest can degrade long before anyone records it.</p><div className="orbit-metric"><strong>18.4<span>pp</span></strong><small>ILLUSTRATIVE CANOPY DECLINE / 2020—2025</small></div></Scene>
  <Scene progress={p} index={2} className="orbit-copy"><p className="eyebrow">02 — ACQUIRE THE SIGNAL</p><h2>One forest.<br/><span>Many wavelengths.</span></h2><p>A different instrument reveals a different truth. <br/>Switch the observation layer.</p><div className="band-selector">{["OPTICAL","SAR","LiDAR"].map(b=><button key={b} aria-pressed={band===b} onClick={()=>setBand(b)}>{b}<span>{b==="OPTICAL"?"REFLECTANCE":b==="SAR"?"BACKSCATTER":"HEIGHT"}</span></button>)}</div><p className="band-explanation">{band==="OPTICAL"?"Sentinel-2 & Landsat / vegetation reflectance and long-term context.":band==="SAR"?"Sentinel-1 / radar backscatter adds structure-sensitive observations through cloud.":"LiDAR / laser returns describe the vertical shape of the canopy."}</p></Scene>
  <Scene progress={p} index={3} className="orbit-copy"><p className="eyebrow">03 — CO-REGISTER / FUSE / RESOLVE</p><h2>Signals become<br/><span>intelligence.</span></h2><p>SylvaSense aligns imagery across sensors and time. <br/>The landscape resolves into individual crowns.</p><div className="signal-equation"><span>SAR</span> + <span>OPTICAL</span> + <span>LiDAR</span><b>↓</b><strong>12,486 CANOPY INSTANCES</strong></div></Scene>
  <Scene progress={p} index={4} className="orbit-copy"><p className="eyebrow">04 — ESTIMATE / COMPARE</p><h2>Read what<br/>the forest<br/><span>holds.</span></h2><div className="orbit-stats"><div><strong>184.6</strong><span>Mg / ha · aboveground biomass</span></div><div><strong>86.8</strong><span>Mg C / ha · stored carbon</span></div><div><strong>32.7</strong><span>ha · change flagged for review</span></div></div><p className="small-copy">Model estimates, not direct carbon measurements. <br/>Repeat observations reveal the direction of change.</p></Scene>
  <Scene progress={p} index={5} className="orbit-copy orbit-final"><p className="eyebrow">05 — RETURN TO EARTH</p><h2>Perspective.<br/>With <span>purpose.</span></h2><p>Turn a signal into an evidence-backed alert. <br/>Send attention where the forest needs it.</p><div className="mission-complete meta">PASS COMPLETE / 03 AREAS PRIORITIZED</div><EndLinks id="02"/></Scene>
 </div><Chrome id="02" progress={p} jump={jump}/></main>;
}
