"use client";
import {useState} from "react";
import type {PointerEvent} from "react";
import {Chrome,Film,EndLinks,useJourney} from "../journey";
import {random,clamp,range} from "../data";
function Clearing(){return <svg className="clearing-map" viewBox="0 0 600 650" preserveAspectRatio="none" aria-hidden="true"><path d="M220 0 246 0 279 70 262 146 326 183 307 270 373 321 357 426 428 517 403 650 370 650 395 532 326 451 342 333 279 285 294 190 232 160 248 80Z"/><path d="m277 181 57-65 81 11 39 68-34 65-113 10ZM326 387l-67-18-58 27 28 64 107 19ZM370 495l75-44 64 28 22 93-109 17Z"/></svg>;}
export default function Witness(){const {progress:p,stage,reduced}=useJourney();const [compare,setCompare]=useState(51),[band,setBand]=useState("RGB"),[reviewed,setReviewed]=useState(false),[selected,setSelected]=useState(0);
 const jump=(index:number)=>{const chapter=document.querySelectorAll<HTMLElement>(".report-chapter")[index-1];const top=index===0?0:chapter.getBoundingClientRect().top+window.scrollY+parseFloat(getComputedStyle(chapter).paddingTop)-(innerWidth<=760?innerHeight*.35+110:innerHeight*.2);window.scrollTo({top:Math.max(0,top),behavior:reduced?"instant":"smooth"});};
 const moveComparison=(e:PointerEvent<HTMLDivElement>)=>{if(stage!==1)return;const box=e.currentTarget.getBoundingClientRect();setCompare(Math.round(clamp((e.clientX-box.left)/box.width)*100));};
 const bandCopy=band==="RGB"?"Optical imagery / visible canopy":band==="NDVI"?"Vegetation index / relative greenness":band==="SAR"?"Radar backscatter / structural change":"LiDAR / relative canopy height";
 return <main className="journey witness"><Chrome id="05" progress={p} jump={jump}/>
 <section className="witness-hero"><Film active={stage===0}/><div className="witness-hero-wash"/><div className="witness-hero-top meta"><span>FIELD REPORT 05—A</span><span>OBSERVATION IS THE FIRST ACT OF CARE.</span></div><div className="witness-hero-title"><p className="eyebrow">05 / THE WITNESS</p><h1>THE FOREST<br/>HAS A<br/><em>WITNESS.</em></h1><div className="witness-hero-bottom"><p>A story of disappearance. <br/>An investigation from above.</p><button onClick={()=>jump(1)}>OPEN THE CASE <span>↓</span></button></div></div><span className="film-code">SYLVA / EXP. 005 / 24 FPS</span></section>
 <div className="witness-dossier"><aside className="witness-evidence"><div className="evidence-caption meta"><span>EXHIBIT {stage<3?"A":stage===3?"B":"C"} / {band}</span><span>AOI—042</span></div><div className={`evidence-image band-${band.toLowerCase()}`} style={{transform:`perspective(1400px) rotateY(${(1-range(p,.13,.25))*-12}deg)`}} onPointerDown={e=>{if(stage===1){e.currentTarget.setPointerCapture(e.pointerId);moveComparison(e);}}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))moveComparison(e);}} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}}><img src="/media/canopy.jpg" alt="Forest canopy used as the base for an illustrative change comparison"/><div className="evidence-after" style={{clipPath:stage===1?`inset(0 0 0 ${compare}%)`:"inset(0 0 0 0)"}}><img src="/media/canopy.jpg" alt=""/><Clearing/></div>{stage===1&&<div className="compare-line" style={{left:`${compare}%`}}><span>↔</span></div>}{stage>=2&&<div className="evidence-targets">{[0,1,2].map((n)=><button key={n} className={selected===n?"selected":""} style={{left:`${[46,56,72][n]}%`,top:`${[25,61,78][n]}%`}} onClick={()=>setSelected(n)} aria-label={`Inspect change zone ${n+1}`}><span>{String(n+1).padStart(2,"0")}</span></button>)}</div>}{stage>=3&&<svg className="witness-centroids" viewBox="0 0 600 650" aria-hidden="true">{Array.from({length:65},(_,i)=><circle key={i} cx={random(i+66)*600} cy={random(i+24)*650} r={4+random(i)*14}/>)}</svg>}<i className="evidence-scan-line" aria-hidden="true" style={{top:`${(p*470)%100}%`,opacity:stage>=3?.65:0}}/><span className="evidence-image-note meta">SIMULATED CHANGE OVER STOCK IMAGERY</span></div>{stage===1?<div className="compare-control"><label htmlFor="comparison">2020 <span>DRAG TO COMPARE</span> 2025</label><input id="comparison" aria-label="Before and after comparison" type="range" min="0" max="100" value={compare} onChange={e=>setCompare(Number(e.target.value))}/></div>:<div className="evidence-legend meta"><span>+ {stage>=3?"CANOPY INSTANCES":"CHANGE BOUNDARY"}</span><span>50 m ━━━━━</span></div>}<div className="evidence-source">{bandCopy}<br/><span>Illustrative scene · not an observed event or location</span></div></aside>
 <div className="witness-report"><section className="report-chapter"><span className="report-kicker">01 — ESTABLISH THE CHANGE</span><h2>Same forest.<br/><em>Different story.</em></h2><p>At first, everything looks green. Compare the years, and a different picture appears: a new access route, fragmented habitat, a thinning canopy.</p><div className="report-number">18.4<span>pp</span></div><p className="report-caption">Illustrative canopy cover decrease <br/>92.1% in 2020 → 73.7% in 2025</p><span className="margin-note">← MOVE THE DIVIDER. LOOK CLOSER.</span></section>
 <section className="report-chapter"><span className="report-kicker">02 — LOOK BETWEEN THE VISITS</span><h2>Small changes.<br/><em>Accumulating.</em></h2><p>A field team cannot be everywhere, every day. Degradation hides in the intervals. Repeated satellite observations help connect those missing moments.</p><div className="evidence-zone-detail"><span className="meta">SELECTED ZONE / 0{selected+1}</span><strong>{["New access corridor","Canopy fragmentation","Expanding clearing"][selected]}</strong><p>{["A linear opening connects previously intact canopy patches.","A connected canopy separates into smaller habitat islands.","The affected boundary widens between successive observations."][selected]}</p><span>{["8.2","10.6","13.9"][selected]} ha · flagged for field verification</span></div><span className="margin-note">← SELECT A NUMBERED CHANGE ZONE.</span></section>
 <section className="report-chapter"><span className="report-kicker">03 — CORROBORATE THE EVIDENCE</span><h2>One source<br/>is <em>not the story.</em></h2><p>Sentinel-2 and Landsat reveal vegetation change. Sentinel-1 radar adds observations through cloud. LiDAR describes the height of what remains.</p><div className="witness-bands" aria-label="Evidence sensor layer">{["RGB","NDVI","SAR","LiDAR"].map(x=><button key={x} onClick={()=>setBand(x)} aria-pressed={band===x}>{x}</button>)}</div><p className="report-caption">{bandCopy}. Colors and geometry simulate the selected output.</p><div className="evidence-stamp">MULTIPLE SIGNALS<br/><strong>ONE LANDSCAPE</strong></div></section>
 <section className="report-chapter"><span className="report-kicker">04 — QUANTIFY THE CONSEQUENCE</span><h2>Put a measure<br/>to <em>the missing.</em></h2><p>SylvaSense turns aligned observations into canopy instances, tree counts, biomass estimates, carbon stock, and a dated record of degradation.</p><div className="witness-chart"><span className="meta">CANOPY COVER / SIMULATED TIME SERIES</span><svg viewBox="0 0 400 145" role="img" aria-label="Canopy cover falls from 92.1 percent in 2020 to 73.7 percent in 2025"><path className="chart-grid" d="M0 30H400M0 70H400M0 110H400"/><path className="chart-area" d="M8 24 85 30 162 47 239 61 316 91 392 122V145H8Z"/><path className="chart-line" d="M8 24 85 30 162 47 239 61 316 91 392 122"/>{[24,30,47,61,91,122].map((y,i)=><circle key={i} cx={8+i*76.8} cy={y} r="3"/>)}</svg><div className="chart-years"><span>2020 / 92.1%</span><span>2025 / 73.7%</span></div></div><dl className="report-metrics"><div><dt>Canopy instances</dt><dd>12,486</dd></div><div><dt>Aboveground biomass</dt><dd>184.6 <small>Mg/ha</small></dd></div><div><dt>Stored carbon</dt><dd>86.8 <small>Mg C/ha</small></dd></div></dl></section>
 <section className="report-chapter report-final"><span className="report-kicker">05 — MAKE IT VERIFIABLE</span><h2>Evidence.<br/>For what<br/><em>comes next.</em></h2><p>An alert is a starting point. Prioritize these three change zones, verify them on the ground, and return to the same evidence after action.</p><div className={`review-status ${reviewed?"is-reviewed":""}`}><span className="meta">STUDY FILE 05—A</span><strong>{reviewed?"Flagged for field verification":"32.7 ha require a closer look"}</strong><button onClick={()=>setReviewed(!reviewed)}>{reviewed?"Reset review":"Mark for field verification"}<span>{reviewed?"↺":"↗"}</span></button><small>{reviewed?"Demo state saved for this session. No alert was sent.":"Prototype interaction · no external alert is sent"}</small></div><EndLinks id="05"/></section></div></div>
 </main>;
}
